---
controller_credentials:
- name: CyberArk Conjur Database - chef_cyberark_vault_fixture
  description: Credential for chef_cyberark_vault_fixture
  organization: Default
  credential_type: CyberArk Conjur Database
  update_secrets: true
  inputs:
    username: '{{ username }}'
    password: '{{ vault_password }}'
    conjur_path_prefix: '{{ conjur_path_prefix }}'
